// === APT HTML Reporter ===
// Generates a self-contained HTML report with inline SVG radar chart.

import { mkdir } from "node:fs/promises";
import type { AnalysisReport, TestDetail, TestDimension } from "@apt/lib/types";

function escapeHtml(str: string | undefined | null): string {
  if (str == null) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export class HtmlReporter {
  async generate(report: AnalysisReport, outputDir: string): Promise<string> {
    const html = this.render(report);
    const path = `${outputDir}/evaluation_${report.evaluation_id}.html`;
    await mkdir(outputDir, { recursive: true });
    await Bun.write(path, html);
    return path;
  }

  private render(report: AnalysisReport): string {
    const passRate = report.test_details
      ? (
          (report.test_details.filter((t) => t.passed).length / report.test_details.length) *
          100
        ).toFixed(1)
      : null;
    const durationStr =
      report.summary.duration_ms > 0 ? this.formatDuration(report.summary.duration_ms) : null;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>APT Evaluation Report -- ${escapeHtml(report.evaluation_id)}</title>
  <style>
${this.renderStyles()}
  </style>
</head>
<body>
  <div class="container">

    <!-- Header -->
    <header class="header">
      <h1>APT &mdash; Evaluation Report</h1>
      <p class="header-meta">${escapeHtml(report.trace.completed_at)} &bull; ID: <code>${escapeHtml(report.evaluation_id)}</code></p>
    </header>

    <!-- Executive Summary -->
    <section class="score-hero">
      <div class="score-value" style="color: ${this.scoreColor(report.summary.overall_score)}">${report.summary.overall_score.toFixed(1)}</div>
      <div class="score-grade">Grade: <span class="grade-badge grade-${escapeHtml(report.summary.overall_grade)}">${escapeHtml(report.summary.overall_grade)}</span></div>
      <div class="score-meta">
        ${report.summary.dimensions_tested} dimensions &bull;
        ${report.summary.total_tests} tests${passRate ? ` &bull; ${passRate}% pass rate` : ""}${durationStr ? ` &bull; ${durationStr}` : ""}
      </div>
      <p class="verdict">${this.verdictText(report.summary.overall_score, report.summary.overall_grade)}</p>
    </section>

    <!-- Human Review Bar -->
    <div id="review-bar" class="review-bar" style="display:none">
      <span>&#128269; <strong id="review-count">0</strong> overrides</span>
      <span>Adjusted: <strong id="adjusted-score">--</strong> <span id="adjusted-grade" class="grade-badge"></span></span>
      <button id="export-btn">Export Review (JSON)</button>
    </div>

    <!-- System Profile -->
    ${this.renderSystemProfile(report)}

    <!-- Dimension Overview -->
    ${
      report.dimensions.length > 2
        ? `
    <h2>Dimension Overview</h2>
    <div class="radar-container">
      ${this.renderRadarChart(report.dimensions)}
    </div>
    `
        : ""
    }

    <!-- Dimension Scores -->
    <h2>Dimension Scores</h2>
    <table>
      <thead>
        <tr><th>Dimension</th><th>Score</th><th>Grade</th><th>Tests</th><th>CI (95%)</th></tr>
      </thead>
      <tbody>
      ${report.dimensions
        .map(
          (d) => `
        <tr>
          <td>${escapeHtml(d.dimension)}</td>
          <td>${this.renderScoreBar(d.normalized_score)}</td>
          <td><span class="grade-badge grade-${escapeHtml(d.grade)}">${escapeHtml(d.grade)}</span></td>
          <td>${d.n_tests}</td>
          <td>[${d.ci_lower.toFixed(2)}, ${d.ci_upper.toFixed(2)}]</td>
        </tr>`,
        )
        .join("")}
      </tbody>
    </table>

    <!-- Recommendations -->
    ${this.renderRecommendations(report)}

    <!-- Test Details -->
    ${this.renderTestDetails(report)}

    <!-- Execution Metadata -->
    ${this.renderExecutionMetadata(report)}

    <!-- Footer -->
    <footer class="footer">
      <p>Generated by APT v${escapeHtml(report.trace.pipeline_version)}</p>
      <p class="disclaimer">This report is generated automatically. Results should be interpreted in context and validated by domain experts.</p>
    </footer>

  </div>
${this.renderReviewScript(report)}
</body>
</html>`;
  }

  private renderStyles(): string {
    return `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f8fafc; color: #1e293b; line-height: 1.6; padding: 2rem; }
    .container { max-width: 960px; margin: 0 auto; }
    .header { margin-bottom: 2rem; }
    .header h1 { font-size: 1.75rem; font-weight: 700; }
    .header-meta { color: #64748b; font-size: 0.875rem; margin-top: 0.25rem; }
    .header-meta code { background: #f1f5f9; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.8rem; }
    h2 { font-size: 1.2rem; margin: 2rem 0 0.75rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.3rem; }
    .score-hero { text-align: center; padding: 2rem; background: white; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 2rem; }
    .score-value { font-size: 4rem; font-weight: 700; }
    .score-grade { font-size: 1.5rem; color: #64748b; }
    .score-meta { color: #94a3b8; font-size: 0.875rem; margin-top: 0.5rem; }
    .verdict { margin-top: 0.75rem; font-size: 0.95rem; color: #475569; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; }
    .grade-badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px; font-weight: 700; font-size: 0.875rem; }
    .grade-A { background: #dcfce7; color: #166534; }
    .grade-B { background: #dbeafe; color: #1e40af; }
    .grade-C { background: #fef9c3; color: #854d0e; }
    .grade-D { background: #fed7aa; color: #9a3412; }
    .grade-F { background: #fecaca; color: #991b1b; }
    .badge { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 4px; font-weight: 600; font-size: 0.75rem; text-transform: uppercase; }
    .badge-pass { background: #dcfce7; color: #166534; }
    .badge-fail { background: #fecaca; color: #991b1b; }
    .recommendation { padding: 0.75rem 1rem; margin: 0.5rem 0; border-radius: 8px; background: white; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
    .prio-high { border-left: 4px solid #ef4444; }
    .prio-medium { border-left: 4px solid #f59e0b; }
    .prio-low { border-left: 4px solid #22c55e; }
    .prio-label { font-weight: 600; font-size: 0.75rem; text-transform: uppercase; }
    .radar-container { text-align: center; margin: 1rem 0; background: white; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }

    /* System profile card */
    .profile-card { background: white; border-radius: 8px; padding: 1.25rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin: 1rem 0; }
    .profile-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
    .profile-item label { display: block; font-size: 0.75rem; text-transform: uppercase; color: #64748b; font-weight: 600; letter-spacing: 0.05em; }
    .profile-item span { font-size: 0.95rem; }

    /* Test details */
    details { margin: 0.5rem 0; }
    details > summary { cursor: pointer; padding: 0.5rem 0.75rem; border-radius: 6px; background: white; box-shadow: 0 1px 2px rgba(0,0,0,0.05); font-weight: 500; list-style: none; }
    details > summary::-webkit-details-marker { display: none; }
    details > summary::before { content: "\\25B6"; display: inline-block; margin-right: 0.5rem; font-size: 0.7rem; transition: transform 0.2s; }
    details[open] > summary::before { transform: rotate(90deg); }
    details[open] > summary { margin-bottom: 0.5rem; }
    .dim-details { padding-left: 1rem; }
    .test-detail-content { padding: 0.75rem 1rem; background: #f8fafc; border-radius: 6px; margin-bottom: 0.5rem; }
    .test-detail-content h4 { font-size: 0.85rem; color: #64748b; text-transform: uppercase; margin: 0.75rem 0 0.25rem; }
    .test-detail-content h4:first-child { margin-top: 0; }
    .code-block { background: #1e293b; color: #e2e8f0; padding: 0.75rem 1rem; border-radius: 6px; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 0.825rem; white-space: pre-wrap; word-break: break-word; max-height: 300px; overflow-y: auto; margin: 0.25rem 0; }
    .eval-table { font-size: 0.85rem; }
    .eval-table th { font-size: 0.7rem; }
    .tag { display: inline-block; background: #e2e8f0; color: #475569; padding: 0.1rem 0.4rem; border-radius: 3px; font-size: 0.75rem; margin-right: 0.25rem; }
    .noise-indicator { display: inline-flex; align-items: center; gap: 0.25rem; font-size: 0.85rem; }
    .noise-ok { color: #16a34a; }
    .noise-warn { color: #ea580c; }
    .irt-info { font-size: 0.85rem; color: #475569; }

    /* Execution metadata */
    .exec-meta { background: white; border-radius: 8px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin: 1rem 0; font-size: 0.875rem; color: #475569; }
    .exec-meta dt { font-weight: 600; color: #1e293b; }
    .exec-meta dd { margin: 0 0 0.5rem 0; }

    /* Footer */
    .footer { color: #94a3b8; font-size: 0.8rem; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; text-align: center; }
    .disclaimer { margin-top: 0.25rem; font-style: italic; }

    /* Human Review */
    .review-bar { position: sticky; top: 0; z-index: 10; background: #1e293b; color: white;
      padding: 0.75rem 1.5rem; border-radius: 8px; display: flex; align-items: center;
      gap: 1.5rem; margin-bottom: 1rem; }
    .override-btn { background: none; border: 1px solid #cbd5e1; border-radius: 4px;
      cursor: pointer; font-size: 0.75rem; padding: 0.1rem 0.4rem; margin-left: 0.5rem;
      opacity: 0.5; transition: opacity 0.2s; }
    .override-btn:hover { opacity: 1; background: #f1f5f9; }
    .overridden { outline: 2px solid #f59e0b; outline-offset: 2px; }
    .review-note { width: 100%; min-height: 2.5rem; margin-top: 0.5rem; padding: 0.5rem;
      border: 1px solid #e2e8f0; border-radius: 6px; font-family: inherit; font-size: 0.85rem;
      resize: vertical; }
    .badge-override { background: #fef3c7; color: #92400e; }
    #export-btn { background: #3b82f6; color: white; border: none; padding: 0.4rem 1rem;
      border-radius: 6px; cursor: pointer; font-weight: 600; font-size: 0.85rem; }
    #export-btn:hover { background: #2563eb; }

    /* Print */
    @media print {
      body { background: white; padding: 0; font-size: 11pt; }
      .container { max-width: 100%; }
      .score-hero, .profile-card, .recommendation, table, details, .exec-meta { box-shadow: none; border: 1px solid #e2e8f0; }
      details { break-inside: avoid; }
      details[open] > .test-detail-content { break-inside: avoid; }
      .code-block { max-height: none; overflow: visible; background: #f1f5f9; color: #1e293b; border: 1px solid #e2e8f0; }
      .radar-container svg { max-width: 250px; }
      .review-bar, .override-btn, .review-note { display: none !important; }
    }`;
  }

  private renderSystemProfile(report: AnalysisReport): string {
    const p = report.system_profile;
    if (!p) return "";

    return `
    <h2>System Under Test</h2>
    <div class="profile-card">
      <div class="profile-grid">
        <div class="profile-item">
          <label>System Type</label>
          <span>${escapeHtml(p.system_type)}</span>
        </div>
        <div class="profile-item">
          <label>Detection Confidence</label>
          <span>${(p.detection_confidence * 100).toFixed(0)}%</span>
        </div>
        <div class="profile-item">
          <label>Detection Methods</label>
          <span>${p.detection_methods.map((m) => `${escapeHtml(m.method)} (${(m.confidence * 100).toFixed(0)}%)`).join(", ")}</span>
        </div>
        <div class="profile-item">
          <label>Capabilities</label>
          <span>${p.capabilities.map((c) => escapeHtml(c)).join(", ") || "none detected"}</span>
        </div>
      </div>
      ${
        p.baseline_metrics
          ? `
      <div class="profile-grid" style="margin-top: 1rem; padding-top: 1rem; border-top: 1px solid #e2e8f0;">
        <div class="profile-item">
          <label>Latency (p50 / p95 / p99)</label>
          <span>${p.baseline_metrics.latency_p50}ms / ${p.baseline_metrics.latency_p95}ms / ${p.baseline_metrics.latency_p99}ms</span>
        </div>
        <div class="profile-item">
          <label>Determinism</label>
          <span>${(p.baseline_metrics.determinism * 100).toFixed(1)}%</span>
        </div>
      </div>`
          : ""
      }
    </div>`;
  }

  private renderRecommendations(report: AnalysisReport): string {
    if (report.recommendations.length === 0) return "";
    return `
    <h2>Recommendations</h2>
    ${report.recommendations
      .map(
        (r) => `
    <div class="recommendation prio-${escapeHtml(r.priority)}">
      <span class="prio-label">${escapeHtml(r.priority)}</span> &mdash; ${escapeHtml(r.description)}
    </div>`,
      )
      .join("")}`;
  }

  private renderTestDetails(report: AnalysisReport): string {
    if (!report.test_details || report.test_details.length === 0) return "";

    // Group tests by dimension
    const byDimension = new Map<TestDimension, TestDetail[]>();
    for (const td of report.test_details) {
      const list = byDimension.get(td.dimension) ?? [];
      list.push(td);
      byDimension.set(td.dimension, list);
    }

    let html = "\n    <h2>Test Details</h2>\n";

    for (const [dim, tests] of byDimension) {
      const passCount = tests.filter((t) => t.passed).length;
      const passPct = ((passCount / tests.length) * 100).toFixed(0);

      html += `
    <details>
      <summary>${escapeHtml(dim)} (${tests.length} tests &mdash; ${passPct}% pass)</summary>
      <div class="dim-details">`;

      for (const t of tests) {
        const statusBadge = t.passed
          ? '<span class="badge badge-pass" data-verdict>PASS</span>'
          : '<span class="badge badge-fail" data-verdict>FAIL</span>';

        html += `
        <details data-test-id="${escapeHtml(t.test_id)}" data-dimension="${escapeHtml(t.dimension)}" data-auto-passed="${t.passed}" data-score="${t.passed ? 1 : 0}">
          <summary>${statusBadge}<button class="override-btn" title="Override verdict">&#8644;</button> ${escapeHtml(t.name)} <span style="color:#94a3b8;font-weight:400">[${t.duration_ms}ms]</span></summary>
          <div class="test-detail-content">`;

        // Description
        if (t.description) {
          html += `
            <h4>Description</h4>
            <p style="font-size:0.9rem">${escapeHtml(t.description)}</p>`;
        }

        // Input
        if (t.input_content) {
          html += `
            <h4>Input</h4>
            <div class="code-block">${escapeHtml(t.input_content)}</div>`;
        }

        // Expected behavior
        if (t.expected_behavior) {
          html += `
            <h4>Expected Behavior</h4>
            <p style="font-size:0.9rem">${escapeHtml(t.expected_behavior)}</p>`;
        }

        // Raw output
        html += `
            <h4>System Response</h4>
            <div class="code-block">${escapeHtml(t.raw_output)}</div>`;

        // Evaluator results
        if (t.evaluator_results.length > 0) {
          html += `
            <h4>Evaluators</h4>
            <table class="eval-table">
              <thead><tr><th>Type</th><th>Result</th><th>Detail</th></tr></thead>
              <tbody>
              ${t.evaluator_results
                .map(
                  (e) => `<tr>
                <td>${escapeHtml(e.type)}</td>
                <td>${e.passed ? '<span class="badge badge-pass">PASS</span>' : '<span class="badge badge-fail">FAIL</span>'}</td>
                <td style="font-size:0.85rem">${escapeHtml(e.detail)}</td>
              </tr>`,
                )
                .join("")}
              </tbody>
            </table>`;
        }

        // Noise indicator
        if (t.noise_cv !== undefined) {
          const noiseClass = t.noise_flag ? "noise-warn" : "noise-ok";
          const noiseIcon = t.noise_flag ? "&#9888;" : "&#10003;";
          html += `
            <h4>Noise</h4>
            <div class="noise-indicator ${noiseClass}">${noiseIcon} CV: ${t.noise_cv.toFixed(3)}${t.noise_flag ? " (flagged)" : ""}</div>`;
        }

        // IRT params
        if (t.irt_params) {
          html += `
            <h4>IRT Parameters</h4>
            <div class="irt-info">Difficulty (&#946;): ${t.irt_params.beta.toFixed(2)} &bull; Discrimination (&#945;): ${t.irt_params.alpha.toFixed(2)} &bull; Guessing (&#947;): ${t.irt_params.gamma.toFixed(2)}</div>`;
        }

        // Compliance tags
        if (t.compliance && t.compliance.length > 0) {
          html += `
            <h4>Compliance</h4>
            <div>${t.compliance.map((c) => `<span class="tag">${escapeHtml(c.standard)} ${escapeHtml(c.article)}</span>`).join(" ")}</div>`;
        }

        // Tags
        if (t.tags.length > 0) {
          html += `
            <h4>Tags</h4>
            <div>${t.tags.map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join(" ")}</div>`;
        }

        // Human Review
        html += `
            <h4>Human Review</h4>
            <textarea class="review-note" placeholder="Add review notes..."></textarea>`;

        html += `
          </div>
        </details>`;
      }

      html += `
      </div>
    </details>`;
    }

    return html;
  }

  private renderReviewScript(report: AnalysisReport): string {
    // Pre-compute dimension weights for score recalculation (equal weight)
    const dimData = report.dimensions.map(d => ({
      dimension: d.dimension,
      weight: 1,
      n_tests: d.n_tests,
    }));

    return `
<script>
(function() {
  var state = { overrides: {} };
  var dimData = ${JSON.stringify(dimData)};

  document.querySelectorAll('.override-btn').forEach(function(btn) {
    btn.addEventListener('click', function(e) {
      e.stopPropagation();
      e.preventDefault();
      var detail = btn.closest('details[data-test-id]');
      if (!detail) return;
      var testId = detail.dataset.testId;
      var autoPassed = detail.dataset.autoPassed === 'true';

      if (state.overrides[testId] !== undefined) {
        delete state.overrides[testId];
        detail.classList.remove('overridden');
      } else {
        state.overrides[testId] = { passed: !autoPassed, note: '' };
        detail.classList.add('overridden');
      }
      updateUI();
    });
  });

  document.querySelectorAll('.review-note').forEach(function(textarea) {
    textarea.addEventListener('input', function() {
      var detail = textarea.closest('details[data-test-id]');
      if (!detail) return;
      var testId = detail.dataset.testId;
      if (state.overrides[testId]) {
        state.overrides[testId].note = textarea.value;
      }
    });
  });

  function updateUI() {
    document.querySelectorAll('details[data-test-id]').forEach(function(detail) {
      var testId = detail.dataset.testId;
      var badge = detail.querySelector('[data-verdict]');
      if (!badge) return;
      var override = state.overrides[testId];
      var passed = override !== undefined ? override.passed : detail.dataset.autoPassed === 'true';

      badge.className = 'badge ' + (passed ? 'badge-pass' : 'badge-fail') + (override !== undefined ? ' badge-override' : '');
      badge.textContent = passed ? (override !== undefined ? 'PASS \\u270E' : 'PASS') : (override !== undefined ? 'FAIL \\u270E' : 'FAIL');
    });

    recalcScores();

    var bar = document.getElementById('review-bar');
    var count = Object.keys(state.overrides).length;
    bar.style.display = count > 0 ? 'flex' : 'none';
    document.getElementById('review-count').textContent = count;
  }

  function recalcScores() {
    var dimScores = {};
    dimData.forEach(function(d) { dimScores[d.dimension] = { pass: 0, total: 0, weight: d.weight }; });

    document.querySelectorAll('details[data-test-id]').forEach(function(detail) {
      var testId = detail.dataset.testId;
      var dim = detail.dataset.dimension;
      var override = state.overrides[testId];
      var passed = override !== undefined ? override.passed : detail.dataset.autoPassed === 'true';

      if (dimScores[dim]) {
        dimScores[dim].total++;
        if (passed) dimScores[dim].pass++;
      }
    });

    var totalWeight = 0;
    var weightedSum = 0;
    Object.keys(dimScores).forEach(function(dim) {
      var d = dimScores[dim];
      if (d.total === 0) return;
      var score = (d.pass / d.total) * 100;
      totalWeight += d.weight;
      weightedSum += score * d.weight;
    });

    var overall = totalWeight > 0 ? weightedSum / totalWeight : 0;
    document.getElementById('adjusted-score').textContent = overall.toFixed(1);

    var gradeEl = document.getElementById('adjusted-grade');
    var grade = overall >= 90 ? 'A' : overall >= 75 ? 'B' : overall >= 60 ? 'C' : overall >= 40 ? 'D' : 'F';
    gradeEl.textContent = grade;
    gradeEl.className = 'grade-badge grade-' + grade;
  }

  document.getElementById('export-btn').addEventListener('click', function() {
    var evalId = '';
    var codeEl = document.querySelector('header code');
    if (codeEl) evalId = codeEl.textContent || '';

    var dimScores = {};
    dimData.forEach(function(d) { dimScores[d.dimension] = { pass: 0, total: 0 }; });
    document.querySelectorAll('details[data-test-id]').forEach(function(detail) {
      var testId = detail.dataset.testId;
      var dim = detail.dataset.dimension;
      var override = state.overrides[testId];
      var passed = override !== undefined ? override.passed : detail.dataset.autoPassed === 'true';
      if (dimScores[dim]) {
        dimScores[dim].total++;
        if (passed) dimScores[dim].pass++;
      }
    });

    var adjustedDims = {};
    Object.keys(dimScores).forEach(function(dim) {
      var d = dimScores[dim];
      adjustedDims[dim] = d.total > 0 ? ((d.pass / d.total) * 100).toFixed(1) : '0.0';
    });

    var data = {
      evaluation_id: evalId,
      reviewed_at: new Date().toISOString(),
      overrides: state.overrides,
      adjusted_dimension_scores: adjustedDims,
      adjusted_overall: document.getElementById('adjusted-score').textContent,
      adjusted_grade: document.getElementById('adjusted-grade').textContent
    };

    var blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'review_' + evalId + '.json';
    a.click();
    URL.revokeObjectURL(url);
  });
})();
</script>`;
  }

  private renderExecutionMetadata(report: AnalysisReport): string {
    const meta = report.execution_metadata_summary;
    return `
    <h2>Execution Metadata</h2>
    <div class="exec-meta">
      <dl>
        ${
          meta
            ? `
        <dt>Strategy</dt><dd>${escapeHtml(meta.strategy)}</dd>
        <dt>Backends</dt><dd>${meta.backends_used.map((b) => escapeHtml(b)).join(", ")}</dd>
        <dt>Total Execution Time</dt><dd>${this.formatDuration(meta.total_duration_ms)}</dd>
        `
            : ""
        }
        <dt>Pipeline Version</dt><dd>${escapeHtml(report.trace.pipeline_version)}</dd>
        <dt>Started</dt><dd>${escapeHtml(report.trace.started_at)}</dd>
        <dt>Completed</dt><dd>${escapeHtml(report.trace.completed_at)}</dd>
        <dt>Modules</dt><dd>${report.trace.modules.map((m) => escapeHtml(m)).join(" &rarr; ")}</dd>
      </dl>
    </div>`;
  }

  private renderRadarChart(dimensions: AnalysisReport["dimensions"]): string {
    const size = 300;
    const cx = size / 2;
    const cy = size / 2;
    const radius = size / 2 - 40;
    const n = dimensions.length;

    let svg = `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">`;

    for (const pct of [20, 40, 60, 80, 100]) {
      const r = (radius * pct) / 100;
      svg += `<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#e2e8f0" stroke-width="1"/>`;
    }

    for (let i = 0; i < n; i++) {
      const angle = (Math.PI * 2 * i) / n - Math.PI / 2;
      const x = cx + radius * Math.cos(angle);
      const y = cy + radius * Math.sin(angle);
      svg += `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#e2e8f0" stroke-width="1"/>`;
      const labelX = cx + (radius + 20) * Math.cos(angle);
      const labelY = cy + (radius + 20) * Math.sin(angle);
      svg += `<text x="${labelX}" y="${labelY}" text-anchor="middle" dominant-baseline="middle" font-size="11" fill="#64748b">${escapeHtml(dimensions[i].dimension)}</text>`;
    }

    const points = dimensions
      .map((d, i) => {
        const angle = (Math.PI * 2 * i) / n - Math.PI / 2;
        const r = (radius * d.normalized_score) / 100;
        return `${cx + r * Math.cos(angle)},${cy + r * Math.sin(angle)}`;
      })
      .join(" ");

    svg += `<polygon points="${points}" fill="rgba(59, 130, 246, 0.2)" stroke="#3b82f6" stroke-width="2"/>`;

    for (let i = 0; i < dimensions.length; i++) {
      const angle = (Math.PI * 2 * i) / n - Math.PI / 2;
      const r = (radius * dimensions[i].normalized_score) / 100;
      svg += `<circle cx="${cx + r * Math.cos(angle)}" cy="${cy + r * Math.sin(angle)}" r="4" fill="#3b82f6"/>`;
    }

    svg += "</svg>";
    return svg;
  }

  private renderScoreBar(score: number): string {
    const color = this.scoreColor(score);
    return `<div style="display:flex;align-items:center;gap:8px"><div style="width:80px;height:8px;background:#e2e8f0;border-radius:4px;overflow:hidden"><div style="width:${score}%;height:100%;background:${color};border-radius:4px"></div></div><span>${score.toFixed(1)}%</span></div>`;
  }

  private scoreColor(score: number): string {
    if (score >= 80) return "#22c55e";
    if (score >= 50) return "#f59e0b";
    return "#ef4444";
  }

  private verdictText(score: number, _grade: string): string {
    if (score >= 85)
      return "The system demonstrates strong overall performance across evaluated dimensions.";
    if (score >= 70) return "The system shows acceptable performance with areas for improvement.";
    if (score >= 55)
      return "The system has notable weaknesses that should be addressed before production use.";
    return "The system has critical deficiencies requiring immediate attention.";
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`;
    const min = Math.floor(ms / 60_000);
    const sec = Math.round((ms % 60_000) / 1000);
    return `${min}m ${sec}s`;
  }
}
